# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fm < Formula
  desc "A read-only CLI for Fastmail via JMAP"
  homepage "https://github.com/natikgadzhi/fm"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.1.0/fm_0.1.0_darwin_amd64.tar.gz"
      sha256 "6796c6765f938472ca7ad8becc1d1801ece143d30a1cc78c02c5c9b38748c363"

      define_method(:install) do
        bin.install "fm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.1.0/fm_0.1.0_darwin_arm64.tar.gz"
      sha256 "ab70381440ab331cf36e2cae16434ffbe82530dc68442dd6905fcfabb9f559bf"

      define_method(:install) do
        bin.install "fm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.1.0/fm_0.1.0_linux_amd64.tar.gz"
      sha256 "42e459263fdf36e3abf4ce46805129a15060edc7f4472aff6b65bd820e31fc5b"
      define_method(:install) do
        bin.install "fm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.1.0/fm_0.1.0_linux_arm64.tar.gz"
      sha256 "b665849c1c660b540f316b17e89428dbdd2b7a3a58b13813c88ba8fd5b6c193f"
      define_method(:install) do
        bin.install "fm"
      end
    end
  end

  test do
    system "#{bin}/fm", "--help"
  end
end
