# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fm < Formula
  desc "A read-only CLI for Fastmail via JMAP"
  homepage "https://github.com/natikgadzhi/fm"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.3.1/fm_0.3.1_darwin_amd64.tar.gz"
      sha256 "e05dd9106930eb8406ff253ac9098b450e909608beae549e40795396570f2dcd"

      define_method(:install) do
        bin.install "fm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.3.1/fm_0.3.1_darwin_arm64.tar.gz"
      sha256 "28ac747c7196f2994ce99da3b40a3df37be31bb0a671991241d42b7ad95b287d"

      define_method(:install) do
        bin.install "fm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.3.1/fm_0.3.1_linux_amd64.tar.gz"
      sha256 "e08414be10950158744be42e343a70c4b935dfafa4c0724e9ba2b39e7c6c6d27"
      define_method(:install) do
        bin.install "fm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.3.1/fm_0.3.1_linux_arm64.tar.gz"
      sha256 "940769123a31d531ad5b4799f2c8d28f183ec9b544139762585e39962b322d15"
      define_method(:install) do
        bin.install "fm"
      end
    end
  end

  test do
    system "#{bin}/fm", "--help"
  end
end
