# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fm < Formula
  desc "A read-only CLI for Fastmail via JMAP"
  homepage "https://github.com/natikgadzhi/fm"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.4.0/fm_0.4.0_darwin_amd64.tar.gz"
      sha256 "978e0c37f3917b71b4b8fd0db531b78437ff47bca0d5d41d15c247ee4fd0cb6a"

      define_method(:install) do
        bin.install "fm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.4.0/fm_0.4.0_darwin_arm64.tar.gz"
      sha256 "5375472781e3ab0e3cd834afa87c4d81b7351fdfe6782e105a2ecfa7e6430aeb"

      define_method(:install) do
        bin.install "fm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.4.0/fm_0.4.0_linux_amd64.tar.gz"
      sha256 "06664e89ca146ba1de82f5c5fbdf0649425ba20598f46401f7afd67cb52d0fda"
      define_method(:install) do
        bin.install "fm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/fm/releases/download/v0.4.0/fm_0.4.0_linux_arm64.tar.gz"
      sha256 "37f6077734924bafa931fb08f43af8dc0692b0c2a01b80731de132226ddf6e2b"
      define_method(:install) do
        bin.install "fm"
      end
    end
  end

  test do
    system "#{bin}/fm", "--help"
  end
end
