# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GdriveCli < Formula
  desc "CLI tool to search and download Google Docs, Sheets, and Slides"
  homepage "https://github.com/natikgadzhi/gdrive-cli"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.2.1/gdrive-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "e77083e891c301016f65c6afa76530701008fd54b34cd982f5643ef1c9fba52d"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.2.1/gdrive-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "335a937c494f6bfdae815e92d5e308cf3ba571256f22fc5b8bd18f3c65bb31ab"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.2.1/gdrive-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "b73ad0194d1ec969a03614546f0d4d7ef9c58b2e1f1e7c0a4fc1c9802b500867"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.2.1/gdrive-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "2a874aa7d41ae0482a9ba1eba6a0dde934e1166cf6bf4c42e2e03e167e3a5524"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end
end
