# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GdriveCli < Formula
  desc "CLI tool to search and download Google Docs, Sheets, and Slides"
  homepage "https://github.com/natikgadzhi/gdrive-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.1.0/gdrive-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "f1918a1121560139d378b68c0228ee6d791fb42046812d1958f42be47467db5a"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.1.0/gdrive-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "20beca161a2a02af6533596882476ff348cc0127acfa04ebc0127913834517c7"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.1.0/gdrive-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "d9014e1c1a0115982dd96c94a2467111e710d89ecbf73c1ccdf48f1c4cd339e8"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.1.0/gdrive-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "56e65d3f40977dc7d1440c5b0040ad4aabac10d4de9c1583d2c6636904713a74"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end
end
