# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GdriveCli < Formula
  desc "CLI tool to search and download Google Docs, Sheets, and Slides"
  homepage "https://github.com/natikgadzhi/gdrive-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.0.2/gdrive-cli_0.0.2_darwin_amd64.tar.gz"
      sha256 "4bf054d2708bae705fb2c58e659e03da2da04b60cda183b5281653b1c6facff0"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.0.2/gdrive-cli_0.0.2_darwin_arm64.tar.gz"
      sha256 "52c06820f8fefe857db1647d3b894f5f0c5af4fd6f025a36fd82f6a2098a5fb8"

      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.0.2/gdrive-cli_0.0.2_linux_amd64.tar.gz"
      sha256 "63b8d667ddcf8199845c40c8ef703d4fc15d5601d62f60dba78fd741fa8d1bbb"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/gdrive-cli/releases/download/v0.0.2/gdrive-cli_0.0.2_linux_arm64.tar.gz"
      sha256 "4e0ee7c3a75d8e57a93568a8cd9ed2fe98497bee2b2b078310129cd3c7226290"
      define_method(:install) do
        bin.install "gdrive-cli"
      end
    end
  end
end
