# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notoma < Formula
  desc "One-way sync tool from Notion to Obsidian"
  homepage "https://github.com/natikgadzhi/notoma"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/notoma/releases/download/v0.0.1/notoma_0.0.1_darwin_amd64.zip"
      sha256 "42dc1e7c01b9d50558296edbe807b8d7cdda6d3ab8b9f3fa68df573cfb22e0a7"

      define_method(:install) do
        bin.install "notoma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/notoma/releases/download/v0.0.1/notoma_0.0.1_darwin_arm64.zip"
      sha256 "c0c067af1e24e8eb27e773f827eca2d4e36e9b9a09f18b30aa64c68bfb6942ef"

      define_method(:install) do
        bin.install "notoma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/notoma/releases/download/v0.0.1/notoma_0.0.1_linux_amd64.tar.gz"
      sha256 "2d1718e1fd2e79889b327d131cdfd6d5250e3a2b13696862c563e4aa570031d6"
      define_method(:install) do
        bin.install "notoma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/notoma/releases/download/v0.0.1/notoma_0.0.1_linux_arm64.tar.gz"
      sha256 "1c2c248641fd56f9355fe82ddfeb6d872e21b73983bb501121152d1cc2d04f5c"
      define_method(:install) do
        bin.install "notoma"
      end
    end
  end

  test do
    system "#{bin}/notoma", "--help"
  end
end
