# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackCli < Formula
  desc "Read-only Slack CLI for fetching messages, threads, and history"
  homepage "https://github.com/natikgadzhi/slack-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/slack-cli/releases/download/v0.4.0/slack-cli_0.4.0_darwin_amd64.zip"
      sha256 "e54b397626edb9ff12d50087bbfe4313a743cdb82032c6d59dcf55d397c544da"

      define_method(:install) do
        bin.install "slack-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/slack-cli/releases/download/v0.4.0/slack-cli_0.4.0_darwin_arm64.zip"
      sha256 "15572aa41225a7f83eccb32a4d4b52f1502feb803e7e9f856ffd1c92eaab892e"

      define_method(:install) do
        bin.install "slack-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/slack-cli/releases/download/v0.4.0/slack-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "d1c816def265429893f57465b1ece2fe680c2bd4f276c1824912b9dae3fbfa5e"
      define_method(:install) do
        bin.install "slack-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/slack-cli/releases/download/v0.4.0/slack-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "e2462ed8f35bae1b2fe269558e18a438d761c72467761238019e2252598d2950"
      define_method(:install) do
        bin.install "slack-cli"
      end
    end
  end

  test do
    system "#{bin}/slack-cli", "--help"
  end
end
