# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackCli < Formula
  desc "Read-only Slack CLI for fetching messages, threads, and history"
  homepage "https://github.com/natikgadzhi/slack-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/natikgadzhi/slack-cli/releases/download/v0.1.0/slack-cli_0.1.0_darwin_amd64.zip"
      sha256 "bc5ace6786e053788ee4d895a1b5caa85f146a7a6d52fe66cfb93d08f11d130a"

      define_method(:install) do
        bin.install "slack-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/natikgadzhi/slack-cli/releases/download/v0.1.0/slack-cli_0.1.0_darwin_arm64.zip"
      sha256 "331b8617e2221cd0695933d6373a03b228e4433cf2466f9e92c63fba2a8232c0"

      define_method(:install) do
        bin.install "slack-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/slack-cli/releases/download/v0.1.0/slack-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "fc68a7105cd167da064d45025163fa75fa20245dee91258b3dce5a0a4e46487b"
      define_method(:install) do
        bin.install "slack-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natikgadzhi/slack-cli/releases/download/v0.1.0/slack-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "f1ff7ea955e5104159a0c5b5bdd1ba26e87988507fef0b0266e1fe1bd38c697b"
      define_method(:install) do
        bin.install "slack-cli"
      end
    end
  end

  test do
    system "#{bin}/slack-cli", "--help"
  end
end
